version: '3'
services:
  flask_app:
    build: .
    image: mtl-backend-arm
    ports:
      - "8001:8001"
  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - flask_app